version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:current
#        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/WarwickMicroscopy/Felix/environment-variables
#          username: $DOCKER_HUB_USER
#          password: $DOCKER_HUB_PASSWORD
jobs:
  felix-GaAs-test:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          sudo apt-get update
          sudo apt-get install libcr-dev mpich2 mpich2-doc
          sudo apt-get install libfftw3-dev libfftw3-doc
          
          cd ./felix-${CIRCLE_SHA1}/;pwd;sed "s/ PLATFORM=INT64Nifort/# PLATFORM=INT64Nifort/g" user.mk | sed "s/# PLATFORM=OPT64NGNU/ PLATFORM=OPT64NGNU/g" >newuser.mk; cp newuser.mk user.mk; make clean; make
          
          cd src; make clean; pwd; ls -al
          
          cd ./samples/GaAs; ../../felix-$CIRCLE_SHA1/felix.OPT64NGNU.d | tee terminal_log.txt
          
          diff -W132 -s ./samples/GaAs/GaAs_Sim_0930A_080x080/GaAs_+0+0+0.bin ./samples/GaAs_short/sample_outputs/GaAs_+0+0+0.bin || true

workflows:
  my-felix-workflow:
    jobs:
      - felix-GaAs-test
